# This file used by make for docker-composer container operations
# including docker image build

services:
  app:
    image: ${APP_IMAGE}
    command:
      --listen=:8080 --path=/data
    labels:
      - traefik.enable=true
      - dcape.traefik.tag=${DCAPE_TAG}
      - traefik.http.routers.${APP_TAG}.rule=Host(`${APP_SITE:?Must be set}`)
      - traefik.http.routers.${APP_TAG}.tls=${USE_TLS}
      - traefik.http.routers.${APP_TAG}.tls.certresolver=default
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./tmp:/data
    build:
      context: .

networks:
  default:
    name: ${DCAPE_NET}
    external: true
